name: tournaments
author: Nico_ND1
version: ${project.version}
main: de.bytemc.tournaments.lobby.TournamentLobbyPlugin
depend: [ responsive ]

commands:
    tournament:
        aliases: [ tournaments ]
